name: ci-go-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # baixa os arquivos do repositorio para a maquina de build
      - uses: actions/setup-go@v2 # action do Go lang
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go